spring:
  profiles:
    default: default

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/article
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        #        SQL: debug
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace
            extract: trace

---
spring:
  config:
    activate:
      on-profile: batch

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 500