
server:
  tomcat:
    mbeanregistry:
      enabled: true # actuator ?? tomcat ??? ? ? ???

spring:
  datasource:

    memo-datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/memo
      username: root
      password: 1234
      hikari:
        connection-timeout: 3000
        validation-timeout: 3000
        minimum-idle: 7
        max-lifetime: 240000
        maximum-pool-size: 20

    todo-datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/todo
      username: root
      password: 1234

#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        highlight_sql: true
#        format_sql: true
#        use_sql_comments: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug
