management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
  #      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
#      base-path: "/manage"
info:
  app:
    name: hello-actuator
    company: jh

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true
