spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:file:./testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
        orm:
          jdbc:
            bind: trace
            extract: trace

---
spring:
  config:
    activate:
      on-profile: batch

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 500