


spring:
  datasource:
    xa:
      memo:
        xa-properties:
          url: jdbc:mysql://localhost:3306/memo?pinGlobalTxToPhysicalConnection=true
          username: root
          password: 1234
        xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        resource-name: memo
        borrow-connection-timeout: 3000
        max-lifetime: 180000
#        keepalive-time: 90000
        maximum-pool-size: 20
      todo:
        xa-properties:
          url: jdbc:mysql://localhost:3307/todo?pinGlobalTxToPhysicalConnection=true
          username: root
          password: 1234
        xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        resource-name: todo
        borrow-connection-timeout: 3000
        max-lifetime: 180000
#        keepalive-time: 90000
        maximum-pool-size: 20
  jta:
    enabled: true
    atomikos:
      properties:
        log-base-dir: logs/jta-logs
        serial-jta-transactions: false

logging:
  level:
    root: info
